Repository kindlyops/deleterious, pull requests merged in 2021-12, with the labels that each got.

#193 rename primary branch from master->main
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-drafter.yml
Labels: chore

#204 Add support for specifying aws profile with CLI flag
  .github/workflows/codeql-analysis.yml
  cmd/orphaned.go
  cmd/root.go
Labels: fix

#208 Better reporting on log group sizes
  cmd/orphaned.go
Labels: fix

#209 adjust autovendor for renovate
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/semgrep-analysis.yml
  .github/workflows/semgrep.yml
Labels: chore

#214 better filtering of log groups owned by active lambdas
  cmd/BUILD.bazel
  cmd/orphaned.go
  vendor/github.com/aws/aws-sdk-go/service/lambda/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/service/lambda/api.go
  vendor/github.com/aws/aws-sdk-go/service/lambda/doc.go
  vendor/github.com/aws/aws-sdk-go/service/lambda/errors.go
  vendor/github.com/aws/aws-sdk-go/service/lambda/service.go
  vendor/github.com/aws/aws-sdk-go/service/lambda/waiters.go
  vendor/modules.txt
Labels: fix

#227 add pagination to stack resources list
  cmd/orphaned.go
Labels: fix

#233 configure codecov
  .github/workflows/ci.yaml
  codecov.yml
Labels: chore

#241 sboms
  .github/workflows/ci.yaml
  .github/workflows/release-publisher.yml
  .goreleaser.yml
Labels: feature

#242 fix goreleaser artifact for linux arm build
  .goreleaser.yml
  goreleaser-post-hook.sh
Labels: fix

#244 restore goreleaser announce config
  .goreleaser.yml
Labels: fix

#246 add user local bazel customization suport
  .bazelrc
  .gitignore
Labels: chore
